# Generated by Django 4.2.11 on 2026-06-25 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_carousel_alter_admin_id_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carouselcourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_slider', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='slider',
            new_name='carousel_slider',
        ),
        migrations.AddField(
            model_name='carousel',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
