# Generated by Django 4.2.11 on 2026-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_department_delete_carouselcourses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_slider', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('descriptiom', models.TextField()),
            ],
        ),
    ]
