# Generated by Django 5.1.15 on 2026-06-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_carousel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel2',
        ),
    ]
